-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 16:25:17 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema alltron_reporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alltron_reporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alltron_reporte` DEFAULT CHARACTER SET utf8 ;
USE `alltron_reporte` ;

-- -----------------------------------------------------
-- Table `alltron_reporte`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`perfil` (
  `pk_perfil` INT NOT NULL AUTO_INCREMENT,
  `perfil` VARCHAR(45) NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_perfil`))
ENGINE = InnoDB;

INSERT INTO `perfil` (`pk_perfil`, `perfil`, `activo`) VALUES (NULL, 'Admin', '1'), (NULL, 'Usuario', '1'), (NULL, 'Técnico', '1');

-- -----------------------------------------------------
-- Table `alltron_reporte`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`usuario` (
  `pk_usuario` INT NOT NULL AUTO_INCREMENT,
  `fk_perfil` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `usuario` VARCHAR(100) NULL,
  `contrasena` VARCHAR(100) NULL,
  `nombre` VARCHAR(45) NULL,
  `a_paterno` VARCHAR(45) NULL,
  `a_materno` VARCHAR(45) NULL,
  `telefono` VARCHAR(15) NULL,
  `observacion` VARCHAR(500) NULL,
  `correo` VARCHAR(100) NULL,
  `fecha_registro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_modificacion` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `nombre_foto` VARCHAR(50) NULL,
  PRIMARY KEY (`pk_usuario`),
  INDEX `fk_usuario_perfil1_idx` (`fk_perfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`fk_perfil`)
    REFERENCES `alltron_reporte`.`perfil` (`pk_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO `usuario` (`pk_usuario`, `fk_perfil`, `codigo`, `usuario`, `contrasena`, `nombre`, `a_paterno`, `a_materno`, `telefono`, `observacion`, `correo`, `fecha_registro`, `fecha_modificacion`, `activo`, `nombre_foto`) VALUES (NULL, '1', NULL, 'Admin', 'fb5310aab58e48bb2191f7e26e6bf27eb89562f9', 'Admin', '*', NULL, NULL, NULL, NULL, CURRENT_TIMESTAMP, NULL, '1', NULL);
-- -----------------------------------------------------
-- Table `alltron_reporte`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`modulo` (
  `pk_modulo` INT NOT NULL,
  `modulo` VARCHAR(100) NULL,
  PRIMARY KEY (`pk_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`perfil_modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`perfil_modulo` (
  `fk_perfil` INT NOT NULL,
  `fk_modulo` INT NOT NULL,
  PRIMARY KEY (`fk_perfil`, `fk_modulo`),
  INDEX `fk_perfil_has_modulo_modulo1_idx` (`fk_modulo` ASC) ,
  INDEX `fk_perfil_has_modulo_perfil_idx` (`fk_perfil` ASC) ,
  CONSTRAINT `fk_perfil_has_modulo_perfil`
    FOREIGN KEY (`fk_perfil`)
    REFERENCES `alltron_reporte`.`perfil` (`pk_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perfil_has_modulo_modulo1`
    FOREIGN KEY (`fk_modulo`)
    REFERENCES `alltron_reporte`.`modulo` (`pk_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`cliente` (
  `pk_cliente` INT NOT NULL AUTO_INCREMENT,
  `cliente` VARCHAR(100) NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `direccion` VARCHAR(300) NULL,
  `telefono` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`pk_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`pregunta` (
  `pk_pregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(100) NOT NULL,
  `respuesta` VARCHAR(300) NULL,
  `tipo` TINYINT NOT NULL DEFAULT 1 COMMENT '1 es texto, 2 es input y 3 es checkbox',
  `activo` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`pk_pregunta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`seccion` (
  `pk_seccion` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(45) NOT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `seccion_base` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pk_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`seccion_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`seccion_pregunta` (
  `pk_seccion_pregunta` INT NOT NULL AUTO_INCREMENT,
  `fk_seccion` INT NOT NULL,
  `fk_pregunta` INT NOT NULL,
  `respuesta` VARCHAR(300) NULL,
  INDEX `fk_seccion_has_pregunta_pregunta1_idx` (`fk_pregunta` ASC) ,
  INDEX `fk_seccion_has_pregunta_seccion1_idx` (`fk_seccion` ASC) ,
  PRIMARY KEY (`pk_seccion_pregunta`),
  CONSTRAINT `fk_seccion_has_pregunta_seccion1`
    FOREIGN KEY (`fk_seccion`)
    REFERENCES `alltron_reporte`.`seccion` (`pk_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion_has_pregunta_pregunta1`
    FOREIGN KEY (`fk_pregunta`)
    REFERENCES `alltron_reporte`.`pregunta` (`pk_pregunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`reporte` (
  `pk_reporte` INT NOT NULL AUTO_INCREMENT,
  `reporte` VARCHAR(45) NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `fecha_registrto` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reporte_base` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pk_reporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`reporte_seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`reporte_seccion` (
  `pk_reporte` INT NOT NULL AUTO_INCREMENT,
  `fk_reporte` INT NOT NULL,
  `fk_seccion` INT NOT NULL,
  `especificacion` VARCHAR(100) NULL COMMENT 'Puede ser el nombre de los equipos',
  INDEX `fk_reporte_has_seccion_seccion1_idx` (`fk_seccion` ASC) ,
  INDEX `fk_reporte_has_seccion_reporte1_idx` (`fk_reporte` ASC) ,
  PRIMARY KEY (`pk_reporte`),
  CONSTRAINT `fk_reporte_has_seccion_reporte1`
    FOREIGN KEY (`fk_reporte`)
    REFERENCES `alltron_reporte`.`reporte` (`pk_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_has_seccion_seccion1`
    FOREIGN KEY (`fk_seccion`)
    REFERENCES `alltron_reporte`.`seccion` (`pk_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`cliente_reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`cliente_reporte` (
  `fk_cliente` INT NOT NULL,
  `fk_reporte` INT NOT NULL,
  `fk_usuario` INT NULL,
  `activo` TINYINT NOT NULL DEFAULT 1,
  `qr_reporte` VARCHAR(100) NULL,
  `es_reporte_base` TINYINT NOT NULL DEFAULT 0 COMMENT '0 es reporte base y 1 es el que contesta los tecnicos',
  `fecha_asignado` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_hora_inicio` TIMESTAMP NULL,
  `fecha_hora_fin` TIMESTAMP NULL,
  `coordenadas` VARCHAR(100) NULL,
  `cliente_reporte_base` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`fk_cliente`, `fk_reporte`),
  INDEX `fk_cliente_has_reporte_reporte1_idx` (`fk_reporte` ASC) ,
  INDEX `fk_cliente_has_reporte_cliente1_idx` (`fk_cliente` ASC) ,
  INDEX `fk_cliente_reporte_usuario1_idx` (`fk_usuario` ASC) ,
  CONSTRAINT `fk_cliente_has_reporte_cliente1`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `alltron_reporte`.`cliente` (`pk_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_reporte_reporte1`
    FOREIGN KEY (`fk_reporte`)
    REFERENCES `alltron_reporte`.`reporte` (`pk_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_reporte_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `alltron_reporte`.`usuario` (`pk_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`log` (
  `pk_log` INT NOT NULL AUTO_INCREMENT,
  `responsable` VARCHAR(100) NULL,
  `accion` VARCHAR(300) NULL,
  `fk_usuario` INT NULL,
  `fk_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_log`),
  INDEX `fk_log_usuario1_idx` (`fk_usuario` ASC) ,
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `alltron_reporte`.`usuario` (`pk_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alltron_reporte`.`qr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alltron_reporte`.`qr` (
  `pk_qr` INT NOT NULL AUTO_INCREMENT,
  `qr` VARCHAR(300) NULL,
  `fk_reporte` INT NOT NULL,
  PRIMARY KEY (`pk_qr`),
  INDEX `fk_qr_reporte_seccion1_idx` (`fk_reporte` ASC) ,
  CONSTRAINT `fk_qr_reporte_seccion1`
    FOREIGN KEY (`fk_reporte`)
    REFERENCES `alltron_reporte`.`reporte_seccion` (`pk_reporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
